### ISSUE TITLE
Cannot find module 'parcel-bundler/src/Logger'

### ISSUE THREAD

**Issue by sergey-shpak** [albinotonnina/parcel-plugin-wrapper#3]
After installing plugin getting following error:
`Cannot find module 'parcel-bundler/src/Logger'`

* installed with npm not yarn, so yarn.lock is ignored

**Comment by ghost** [comment]
I'm getting this same error as well. Looks like Logger.js was removed from parcel-bundler.

**Comment by albinotonnina** [comment]
Hi, thanks both of you!
@sergey-shpak thank you very much for the PR! Merged and published new version.
I'm afraid I had issues with my notifications on GitHub. Didn't get any for your PR.
@asdeev please import the new version with the fix @sergey-shpak added in #4

**Comment by ghost** [comment]
> Hi, thanks both of you!
> @sergey-shpak thank you very much for the PR! Merged and published new version.
> I'm afraid I had issues with my notifications on GitHub. Didn't get any for your PR.
> @asdeev please import the new version with the fix @sergey-shpak added in #4

Awesome, looks like it's working perfectly now! 👍
