### ISSUE TITLE
Using multiple entry points results in undefined bundle name

### ISSUE THREAD

**Issue by dbilgili** [albinotonnina/parcel-plugin-wrapper#6]
Using multiple entry points when bundling causes`bundle.name` to be undefined.

https://github.com/albinotonnina/parcel-plugin-wrapper/blob/95d7a81bed0b2f36b14b72cfea9baf95e29e6ea8/index.js#L25

Which results in an error to be caught

https://github.com/albinotonnina/parcel-plugin-wrapper/blob/95d7a81bed0b2f36b14b72cfea9baf95e29e6ea8/index.js#L44-L48

Checking if `name` is `undefined` solves the problem

```
const processAsset = async (bundle, processFn) => {
  const {name} = bundle

  if (name) {
    const wrappingCode = await processFn({name, bundler})

    if (wrappingCode) {
      writeAsset(name, wrappingCode)
    }
  }

  bundle.childBundles.forEach(function(bundle) {
    processAsset(bundle, processFn)
  })
}
```

**Comment by jacksteamdev** [comment]
This would be a great PR. I'd use the fork!

**Comment by albinotonnina** [comment]
I agree @jacksteamdev!
Thank you @dbilgili you feel like making a PR?

**Comment by dbilgili** [comment]
@albinotonnina Opened a PR 👍🏻
